# OBJS = parser.cmo scanner.cmo semant.cmo

default: pixmix.native

.PHONY : pixmix.native

pixmix.native :
	@rm lib/utils.bc parser.ml parser.mli | true
	ocamlbuild -use-ocamlfind -pkgs llvm,llvm.analysis,llvm.linker,llvm.bitreader,llvm.irreader -cflags -w,+a-4 pixmix.native
	clang -emit-llvm -o lib/utils.bc -c lib/utils.c -Wno-varargs

OBJS = ast.cmx codegen.cmx parser.cmx pixmix.cmx sast.cmx scanner.cmx semant.cmx

pixmix: $(OBJS)
	ocamlfind ocamlopt -linkpkg -package llvm -package llvm.analysis $(OBJS) -o pixmix

scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc parser.mly

%.cmo : %.ml
	ocamlc -c $<

%.cmi : %.mli
	ocamlc -c $<

%.cmx : %.ml
	ocamlfind ocamlopt -c -package llvm $<

.PHONY : clean
clean :
	ocamlbuild -clean | true
	rm -f pixmix.native
	rm -f lib/utils.bc
	rm -f *.cmx *.cmi *.cmo *.cmx *.o* *.ll *.exe
	rm -f pixmix parser.ml parser.mli scanner.ml *.cmo *.cmi

.PHONY : debug
debug:
	@make
	OCAMLRUNPARAM='p' ocamlyacc -v parser.mly

.PHONY : tests
tests :
	@make
	@./testall.sh

.PHONY : test
test :
	@make
	@clang -emit-llvm -o lib/utils.bc -c lib/utils.c -Wno-everything
	@./pixmix.native test.pm > test.ll
	@clang -Wno-override-module lib/utils.bc test.ll -o test.exe
	@./test.exe
	@rm test.ll
	@rm test.exe

.PHONY : debugtest
debugtest :
	@make
	@OCAMLRUNPARAM='p' make test

### Generated by "ocamldep *.ml *.mli" after building scanner.ml and parser.ml
ast.cmo :
ast.cmx :
codegen.cmo : sast.cmo
codegen.cmx : sast.cmx
old-sast.cmo :
pixmix.cmo : semant.cmo codegen.cmo ast.cmo
pixmix.cmx : semant.cmx codegen.cmx ast.cmx
sast.cmo : ast.cmo
sast.cmx : ast.cmx
semant.cmo : sast.cmo
semant.cmx : sast.cmx