# OBJS = parser.cmo scanner.cmo semant.cmo

default: pixmix.native

.PHONY : pixmix.native

pixmix.native :
	ocamlbuild -use-ocamlfind -pkgs llvm,llvm.analysis,llvm.linker,llvm.bitreader,llvm.irreader -cflags -w,+a-4 pixmix.native;
	clang -emit-llvm -o utils.bc -c lib/utils.c -Wno-varargs

OBJS = organizer.cmx sast.cmx ast.cmx codegen.cmx parser.cmx scanner.cmx semant.cmx pixmix.cmx parserize.cmx

pixmix: $(OBJS)
	ocamlfind ocamlopt -linkpkg -package llvm -package llvm.analysis $(OBJS) -o pixmix

scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc parser.mly

%.cmo : %.ml
	ocamlc -c $<

%.cmi : %.mli
	ocamlc -c $<

%.cmx : %.ml
	ocamlfind ocamlopt -c -package llvm $<

.PHONY : clean
clean :
	ocamlbuild -clean | true
	rm -f pixmix.native
	rm -f utils.bc
	rm -f *.cmx *.cmi *.cmo *.cmx *.o
	rm -f pixmix parser.ml parser.mli scanner.ml *.cmo *.cmi

.PHONY : debug
debug:
	OCAMLRUNPARAM='p' ocamlyacc -v parser.mly

.PHONY : tests
tests :
	@./testall.sh

.PHONY : test
test :
	@clang -emit-llvm -o utils.bc -c lib/utils.c -Wno-everything
	@./pixmix.native test.pm > test.ll
	@clang -Wno-override-module utils.bc test.ll -o test.exe
	@./test.exe
	@rm test.ll
	@rm test.exe

.PHONY : debugtest
debugtest :
	@OCAMLRUNPARAM='p' make test

### Generated by "ocamldep *.ml *.mli" after building scanner.ml and parser.ml
ast.cmo :
ast.cmx :
sast.cmo : ast.cmo
sast.cmx : ast.cmx
codegen.cmo : sast.cmo
codegen.cmx : sast.cmx
pixmix.cmo : semant.cmo scanner.cmo parser.cmi codegen.cmo ast.cmo
pixmix.cmx : semant.cmx scanner.cmx parser.cmx codegen.cmx ast.cmx
parser.cmo : ast.cmo parser.cmi
parser.cmx : ast.cmx parser.cmi
scanner.cmo : parser.cmi
scanner.cmx : parser.cmx
semant.cmo : ast.cmo
semant.cmx : ast.cmx
parser.cmi : ast.cmo
parserize.cmx : ast.cmo
